### PR TITLE
fix(previews): update preview assets to match impish shell theme

### LINKED ISSUE #26: 21.10: theme switcher preview images could use an update
Screenshot from 2021-10-08 10-32-14

### PR DESCRIPTION
**Pull request by isantop**
Fixes #26

### CODE REVIEW

**Comment by ids1024** [comment]
>  I would have assumed they were using the same library. What's the process to get the change into G-C-C once this is merged?

This used to be used directly by Gnome Control Center, but is now used as a library statically linked into `desktop-widget`. So that will have to be updated.

**Comment by isantop** [comment]
Any updates on this change? Is it good to merge now?

**Comment by jackpot51** [comment]
We just need QA to approve

**Comment by jacobgkau** [comment]
Sorry to nitpick again, but I noticed a difference in the light theme that's related to the actual styling. The preview shows a black (or dark grey) border around the pop-out, while the actual menu has a white (or light grey) border. It's most noticeable when looking at the left side of the selected WiFi network.

Screenshot from 2021-10-21 09-19-53

I had noticed one other thing before this, the `Bluetooth` entry should actually say `Bluetooth On` or else it wouldn't be visible. (And the horizontal rule section separaters in the dark theme seem a little fainter in the previews than in the actual menu, but that one might just be my eyes playing tricks on me.)

**Comment by isantop** [comment]
The icons have been updated to match the updated Icon theme

**Comment by jacobgkau** [comment]
> The icons have been updated to match the updated Icon theme

I'm not seeing them updated on 872a469:

Screenshot from 2021-11-02 12-50-04

The top-right corner still has the old volume icon that's taller than the WiFi icon. Additionally, there's now a bug in the dark theme preview where the in-menu volume icon is missing (or the wrong color).

**Comment by isantop** [comment]
@jacobgkau So, not sure what is wrong with inkscape there, but I had to hand-edit the XML to make the updated icon visible. Hopefully we don't need to worry about that anymore.

**Review by jacobgkau — APPROVED** [review]
All looks good now:
Screenshot from 2021-11-04 10-32-17

**Pull request merged**
