### PR TITLE
Update screenshots to reflect final design

### PR DESCRIPTION
**Pull request by isantop**
This updates the screenshots in the switcher to reflect the final version of the design of the system menu, without the graphics glitches present from running on 19.04.

Light mode screenshot:
light

Dark mode screenshot:
dark

### CODE REVIEW

**Comment by isantop** [comment]
@mmstick @brs17 I can't seem to request reviews from @pop-os/engineering or @pop-os/quality-assurance on this repository.

**Comment by isantop** [comment]
@mmstick The images are being drawn at a very large size on LoDPI. We should halve the resolution on LoDPI devices, which will ensure crisp drawing in either HiDPI or LoDPI

**Comment by isantop** [comment]
Another possibility might be drawing these are grids and using CSS to set the images as background images of those grids. That will allow the grids to be resized fairly freeform.

**Comment by isantop** [comment]
@mmstick I added in the SVG files if you want to put those in. I'm not great with Rust, so I think it would be best if you did that.

**Comment by mmstick** [comment]
Currently making the changes to render SVG images to our [gtk-extras](https://github.com/pop-os/gtk-extras/commits/master) repo.

**Comment by jackpot51** [comment]
Theme switcher is failing to build:

```
error[E0119]: conflicting implementations of trait `std::convert::Into<gtk::auto::drawing_area::DrawingArea>` for type `widgets_::svg_image::SvgImage`:
```

**Comment by mmstick** [comment]
I'm adding the SVG support to this at the moment, so it's failing until I complete it

**Comment by brs17** [comment]
These svgs don't look exactly like screenshots, nor do they look super sharp (I don't think).
Screenshot from 2019-10-15 19-08-55

Is that intentional?

**Pull request merged**
